### ISSUE TITLE
webpack版本问题导致demo无法正常运行

### ISSUE THREAD

**Issue by Kxrr** [ruanyf/jstraining#30]
运行`redux-demo`时报错如下:

```

kxrr:redux-demo/ (master) $ npm start                                                                                                                                                             [17:36:32]

> redux-demo@1.0.0 start /Users/kxrr/PycharmProject/jstraining/demos/redux-demo
> webpack-dev-server --devtool eval --progress --hot --content-base app

/Users/kxrr/PycharmProject/jstraining/demos/redux-demo/node_modules/.2.2.1@webpack/lib/webpack.js:19
		throw new WebpackOptionsValidationError(webpackOptionsValidationErrors);
		^

WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.entry should be one of these:
   object { <key>: non-empty string | [non-empty string] } | non-empty string | [non-empty string] | function
   The entry point(s) of the compilation.
   Details:
    * configuration.entry should be an object.
    * configuration.entry should be a string.
    * configuration.entry should NOT have duplicate items (items ## 1 and 2 are identical) ({
        "keyword": "uniqueItems",
        "dataPath": ".entry",
        "schemaPath": "#/definitions/common.nonEmptyArrayOfUniqueStringValues/uniqueItems",
        "params": {
          "i": 2,
          "j": 1
        },
        "message": "should NOT have duplicate items (items ## 1 and 2 are identical)",
        "schema": true,
        "parentSchema": {
          "items": {
            "minLength": 1,
            "type": "string"
          },
          "minItems": 1,
          "type": "array",
          "uniqueItems": true
        },
        "data": [
          "/Users/kxrr/PycharmProject/jstraining/demos/redux-demo/node_modules/.1.16.3@webpack-dev-server/client/index.js?http://localhost:8080",
          "webpack/hot/dev-server",
          "webpack/hot/dev-server",
          "webpack-dev-server/client?http://localhost:8080",
          "/Users/kxrr/PycharmProject/jstraining/demos/redux-demo/app/main.jsx"
        ]
      }).
      [non-empty string]
    * configuration.entry should be an instance of function
      function returning an entry object or a promise..
 - configuration.resolve.extensions[0] should not be empty.
    at webpack (/Users/kxrr/PycharmProject/jstraining/demos/redux-demo/node_modules/.2.2.1@webpack/lib/webpack.js:19:9)
    at processOptions (/Users/kxrr/PycharmProject/jstraining/demos/redux-demo/node_modules/.1.16.3@webpack-dev-server/bin/webpack-dev-server.js:209:13)
    at Object.<anonymous> (/Users/kxrr/PycharmProject/jstraining/demos/redux-demo/node_modules/.1.16.3@webpack-dev-server/bin/webpack-dev-server.js:228:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)

npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! redux-demo@1.0.0 start: `webpack-dev-server --devtool eval --progress --hot --content-base app`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the redux-demo@1.0.0 start script 'webpack-dev-server --devtool eval --progress --hot --content-base app'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the redux-demo package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --devtool eval --progress --hot --content-base app
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs redux-demo
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls redux-demo
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/kxrr/PycharmProject/jstraining/demos/redux-demo/npm-debug.log
```

应该是在配置中指定`webpack`版本为`latest`(目前为2.2.1)导致的, 尝试使用`npm install webpack@1.13.3 --save`可以解决这个问题

**Comment by ruanyf** [comment]
谢谢指出，我已经在 package.json 里面改过来了。你再重装依赖试试看。
